server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: smarttrip-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/smarttrip_db
      auto-index-creation: true


app:
  jwt:
    secret: 9a6f8b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a
    expiration-ms: 86400000 
logging:
  level:
    root: INFO
    com.smarttrip: DEBUG
